# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
export HADOOP_HOME=/usr/local/hadoop/
export SPARK_HOME=/usr/local/spark/
export JAVA_HOME=/jdk
export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop