# openssl3-rsamb-qat-sw

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG RELEASE

FROM qatsw-crypto-base-ssl3-ubuntu${RELEASE}

COPY script/run_test.sh /
RUN  mkfifo /export-logs
CMD  (/run_test.sh; echo $? > status) 2>&1 | tee output.logs && \
     tar cf /export-logs status output.logs && \
     sleep infinity
