# dlrm-pytorch-model-24.04

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG OS_VER="24.04"
ARG OS_IMAGE="ubuntu"

FROM ${OS_IMAGE}:${OS_VER} as build

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -o Acquire::Check-Date=false update && \
    apt install -y wget

ARG MODEL_WEIGHTS_VER="tb00_40M"
ARG MODEL_WEIGHTS_REPO="https://dlrm.s3-us-west-1.amazonaws.com/models/${MODEL_WEIGHTS_VER}.pt"

# Download model
RUN mkdir -p /model && cd /model && \
    wget --progress=bar:force:noscroll ${MODEL_WEIGHTS_REPO}

FROM scratch

COPY --from=build /model/ /model/
