# ai-common-img
FROM scratch
#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
COPY libs/*.sh /home/ai_common/libs/
COPY libs/*.py /home/ai_common/libs/
