# calicovpp_dsa_agent

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG RELEASE
ARG OS_IMAGE=ubuntu
ARG OS_VER=20.04
FROM calicovpp_dsa_build_base${RELEASE} as builder
FROM ${OS_IMAGE}:${OS_VER}

ARG CALICOVPP_DIR=/vpp-dataplane
ARG CALICOVPP_AGENT_DIR=${CALICOVPP_DIR}/calico-vpp-agent

COPY --from=builder ${CALICOVPP_AGENT_DIR}/dep/gobgp /bin/gobgp
COPY --from=builder ${CALICOVPP_AGENT_DIR}/cmd/debug /bin/debug
COPY --from=builder ${CALICOVPP_AGENT_DIR}/cmd/felix-api-proxy /bin/felix-api-proxy
COPY --from=builder ${CALICOVPP_AGENT_DIR}/cmd/calico-vpp-agent /bin/calico-vpp-agent

ENTRYPOINT ["/bin/calico-vpp-agent"]
