#!/bin/bash -e

### Mysql exposed parameters
export MYSQL_DEFAULT_AUTHENTICATION_PLUGIN=${MYSQL_DEFAULT_AUTHENTICATION_PLUGIN:-mysql_native_password}
# general
export MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS:-4000}
export MYSQL_TABLE_OPEN_CACHE=${MYSQL_TABLE_OPEN_CACHE:-8000}
export MYSQL_TABLE_OPEN_CACHE_INSTANCES=${MYSQL_TABLE_OPEN_CACHE_INSTANCES:-16}
export MYSQL_BACK_LOG=${MYSQL_BACK_LOG:-1500}
export MYSQL_DEFAULT_PASSWORD_LIFETIME=${MYSQL_DEFAULT_PASSWORD_LIFETIME:-0}
export MYSQL_SSL=${MYSQL_SSL:-0}
export MYSQL_PERFORMANCE_SCHEMA=${MYSQL_PERFORMANCE_SCHEMA:-OFF}
export MYSQL_MAX_PREPARED_STMT_COUNT=${MYSQL_MAX_PREPARED_STMT_COUNT:-128000}
export MYSQL_SKIP_LOG_BIN=${MYSQL_SKIP_LOG_BIN:-1}
export MYSQL_CHARACTER_SET_SERVER=${MYSQL_CHARACTER_SET_SERVER:-latin1}
export MYSQL_COLLATION_SERVER=${MYSQL_COLLATION_SERVER:-latin1_swedish_ci}
export MYSQL_TRANSACTION_ISOLATION=${MYSQL_TRANSACTION_ISOLATION:-REPEATABLE-READ}
# files
export MYSQL_INNODB_FILE_PER_TABLE=${MYSQL_INNODB_FILE_PER_TABLE:-ON}
export MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-1024M}
# export MYSQL_INNODB_LOG_FILES_IN_GROUP=${MYSQL_INNODB_LOG_FILES_IN_GROUP:-32}
export MYSQL_INNODB_OPEN_FILES=${MYSQL_INNODB_OPEN_FILES:-4000}
# buffers
export MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-96G}
# export MYSQL_INNODB_BUFFER_POOL_INSTANCES=${MYSQL_INNODB_BUFFER_POOL_INSTANCES:-16}
export MYSQL_INNODB_LOG_BUFFER_SIZE=${MYSQL_INNODB_LOG_BUFFER_SIZE:-64M}
# tune
export MYSQL_INNODB_DOUBLEWRITE=${MYSQL_INNODB_DOUBLEWRITE:-0}
export MYSQL_INNODB_THREAD_CONCURRENCY=${MYSQL_INNODB_THREAD_CONCURRENCY:-0}
export MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT=${MYSQL_INNODB_FLUSH_LOG_AT_TRX_COMMIT:-0}
export MYSQL_INNODB_MAX_DIRTY_PAGES_PCT=${MYSQL_INNODB_MAX_DIRTY_PAGES_PCT:-90}
export MYSQL_INNODB_MAX_DIRTY_PAGES_PCT_LWM=${MYSQL_INNODB_MAX_DIRTY_PAGES_PCT_LWM:-10}
export MYSQL_JOIN_BUFFER_SIZE=${MYSQL_JOIN_BUFFER_SIZE:-32K}
export MYSQL_SORT_BUFFER_SIZE=${MYSQL_SORT_BUFFER_SIZE:-32K}
export MYSQL_INNODB_USE_NATIVE_AIO=${MYSQL_INNODB_USE_NATIVE_AIO:-1}
export MYSQL_INNODB_STATS_PERSISTENT=${MYSQL_INNODB_STATS_PERSISTENT:-1}
export MYSQL_INNODB_SPIN_WAIT_DELAY=${MYSQL_INNODB_SPIN_WAIT_DELAY:-6}
export MYSQL_INNODB_MAX_PURGE_LAG_DELAY=${MYSQL_INNODB_MAX_PURGE_LAG_DELAY:-300000}
export MYSQL_INNODB_MAX_PURGE_LAG=${MYSQL_INNODB_MAX_PURGE_LAG:-0}
export MYSQL_INNODB_CHECKSUM_ALGORITHM=${MYSQL_INNODB_CHECKSUM_ALGORITHM:-none}
export MYSQL_INNODB_IO_CAPACITY=${MYSQL_INNODB_IO_CAPACITY:-4000}
export MYSQL_INNODB_IO_CAPACITY_MAX=${MYSQL_INNODB_IO_CAPACITY_MAX:-20000}
export MYSQL_INNODB_LRU_SCAN_DEPTH=${MYSQL_INNODB_LRU_SCAN_DEPTH:-9000}
export MYSQL_INNODB_CHANGE_BUFFERING=${MYSQL_INNODB_CHANGE_BUFFERING:-none}
export MYSQL_INNODB_READ_ONLY=${MYSQL_INNODB_READ_ONLY:-0}
export MYSQL_INNODB_PAGE_CLEANERS=${MYSQL_INNODB_PAGE_CLEANERS:-4}
export MYSQL_INNODB_UNDO_LOG_TRUNCATE=${MYSQL_INNODB_UNDO_LOG_TRUNCATE:-off}
# perf special
export MYSQL_INNODB_ADAPTIVE_FLUSHING=${MYSQL_INNODB_ADAPTIVE_FLUSHING:-1}
export MYSQL_INNODB_FLUSH_NEIGHBORS=${MYSQL_INNODB_FLUSH_NEIGHBORS:-0}
export MYSQL_INNODB_READ_IO_THREADS=${MYSQL_INNODB_READ_IO_THREADS:-16}
export MYSQL_INNODB_WRITE_IO_THREADS=${MYSQL_INNODB_WRITE_IO_THREADS:-16}
export MYSQL_INNODB_PURGE_THREADS=${MYSQL_INNODB_PURGE_THREADS:-4}
export MYSQL_INNODB_ADAPTIVE_HASH_INDEX=${MYSQL_INNODB_ADAPTIVE_HASH_INDEX:-0}

### WSF optimized
export MYSQL_INNODB_SPIN_WAIT_PAUSE_MULTIPLIER=${MYSQL_INNODB_SPIN_WAIT_PAUSE_MULTIPLIER:-50}
export MYSQL_INNODB_SYNC_SPIN_LOOPS=${MYSQL_INNODB_SYNC_SPIN_LOOPS:-90}
# Intel SSDs perform better with a 4096 Byte (4KB) alignment, refer to https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/ssd-server-storage-applications-paper.pdf
export MYSQL_INNODB_PAGE_SIZE=${MYSQL_INNODB_PAGE_SIZE:-16K} # by default with mysql default value 16K compatible with some Cloud disk without 4K alignment supported

# mysqltuner.pl recommendations
export MYSQL_INNODB_BUFFER_POOL_INSTANCES=${MYSQL_INNODB_BUFFER_POOL_INSTANCES:-64}
# (MYSQL_INNODB_LOG_FILES_IN_GROUP * MYSQL_INNODB_LOG_FILE_SIZE) = 25% of buffer pool size
export MYSQL_INNODB_LOG_FILES_IN_GROUP=${MYSQL_INNODB_LOG_FILES_IN_GROUP:-24}
export MYSQL_THREAD_CACHE_SIZE=${MYSQL_THREAD_CACHE_SIZE:-300}

# log settings
export MYSQL_LOG_DIR=${MYSQL_LOG_DIR:-"/var/log/mysql"}

function scale_mysql_gated_params() {
    export MYSQL_INNODB_BUFFER_POOL_SIZE=1G
    export MYSQL_INNODB_BUFFER_POOL_INSTANCES=1
}
