# smartscience-mysql

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
FROM mysql

ENV AUTO_RUN_DIR /docker-entrypoint-initdb.d

ENV FILE create_sql.sql

COPY ./$FILE $AUTO_RUN_DIR/

RUN chmod -R 775 $AUTO_RUN_DIR
