# smartscience-rtsp

ARG RTSP_VER=0.21.5
FROM aler9/rtsp-simple-server:v${RTSP_VER} AS rtsp
FROM ubuntu:18.04
RUN apt-get -y update
RUN apt-get install -y ffmpeg git
COPY --from=rtsp /rtsp-simple-server /
COPY --from=rtsp /rtsp-simple-server.yml /

RUN mkdir Smart-Science-Lab && cd Smart-Science-Lab && mkdir smartlab-demo && cd smartlab-demo
COPY script/ /Smart-Science-Lab/smartlab-demo/
WORKDIR /

COPY run_rtsp.sh ./
RUN apt-get install -y netcat
CMD bash run_rtsp.sh
