# cdn-nginx-content-server

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG OS_VER=24.04
ARG OS_IMAGE=ubuntu
FROM ${OS_IMAGE}:${OS_VER}

RUN apt-get update && apt-get install -y --no-install-recommends python3 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY /script/http_obj_gen.py /http_obj_gen_new.py

ENTRYPOINT ["nohup","python3","http_obj_gen_new.py"]