# speccpu-2017-v119-gcc-12.1.0-20220509-nda

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG OS_VER=22.04
ARG OS_IMAGE=ubuntu

ARG RELEASE
FROM speccpu-2017-v119-base-nda${RELEASE} as build

# All 1.1.x binaries are compatible with 1.1.9 (or whatever latest cpu2017 version would be).
ARG SPEC2017_ISO_VER=1.1.9
ARG SPEC_CPU_GCC_BINARIES_VER=gcc12.1.0-lin-binaries-20220509
ARG SPEC_CPU_GCC_BINARIES_REPO=${SPEC_CPU_GCC_BINARIES_REPO:-FOR-INTEL-cpu2017-$SPEC2017_ISO_VER-$SPEC_CPU_GCC_BINARIES_VER.tar.xz}

ARG WORK_DIR=/opt/spec2017
WORKDIR ${WORK_DIR}

RUN apt-get update && apt-get install -y --no-install-recommends wget ca-certificates && \
    mkdir -p ${WORK_DIR}/data/
    
ARG URL=${SPEC_CPU_GCC_BINARIES_REPO}
COPY data/ ${WORK_DIR}/data/
RUN [ -e ${WORK_DIR}/data/gcc_binaries.tar.xz ] || wget --no-proxy -T 5 --tries=inf -O ${WORK_DIR}/data/gcc_binaries.tar.xz $URL
RUN tar xfJ ${WORK_DIR}/data/gcc_binaries.tar.xz -C ${WORK_DIR}/

RUN rm -rf ${WORK_DIR}/data/

WORKDIR /opt/spec2017/lib
RUN ln -s libgomp.so libgomp.so.1

FROM ${OS_IMAGE}:${OS_VER}

RUN apt-get update && apt-get install -y --no-install-recommends libnsl2 dmidecode numactl libgomp1 gcc-12 gfortran-11 sudo && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY --from=build /opt/spec2017 /opt/spec2017
COPY script/main-gcc.sh /opt/spec2017/

ENV LD_LIBRARY_PATH=/opt/spec2017/lib/intel64:/opt/spec2017/lib
WORKDIR /opt/spec2017
RUN chmod +x /opt/spec2017/main-gcc.sh

RUN mkfifo /export-logs
CMD (./main-gcc.sh; echo $? > status) 2>&1 | tee output.logs && \
    tar cf /export-logs status output.logs $(find result -type f) && \
    sleep infinity
