# specjbb-2015-zulu-19.30.11

ARG ARCH
FROM specjbb-2015-scripts${ARCH}${RELEASE} AS scripts
FROM specjbb-2015-base${ARCH}${RELEASE}

ARG PACKAGE_ARCH
ARG ZULU_VERSION=zulu19.30.11
ARG ZULU_PACKAGE="https://cdn.azul.com/zulu/bin/zulu19.30.11-ca-jdk19.0.1-linux_${PACKAGE_ARCH}.tar.gz"

ARG JDK_INSTALL_DIR=/opt

WORKDIR ${JDK_INSTALL_DIR}

RUN curl -L "${ZULU_PACKAGE}" -o "${ZULU_VERSION}.tar.gz" && \
  tar -xvf "${ZULU_VERSION}.tar.gz" && \
  rm -f "${ZULU_VERSION}.tar.gz"

USER root

ARG ZULU_VERSION_DIR="${ZULU_VERSION}-ca-jdk19.0.1-linux_${PACKAGE_ARCH}"

RUN cd ${ZULU_VERSION_DIR} && \
  update-alternatives --install /usr/bin/java java ${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin/java 2 && \
  update-alternatives --install /usr/bin/jar jar ${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin/jar 2 && \
  update-alternatives --install /usr/bin/javac javac ${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin/javac 2 && \
  update-alternatives --set jar ${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin/jar && \
  update-alternatives --set javac ${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin/javac

USER ${WORKLOAD_USER}  

ENV JAVA_HOME=${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/ \
  JRE_HOME=${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/jre/ \
  PATH=${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/bin:$PATH:${JDK_INSTALL_DIR}/${ZULU_VERSION_DIR}/jre/bin

WORKDIR /opt/pkb

# Scripts are copied as the last layer in the image to speed-up the builds
# The layers before are not changing so any change in the scripts has effect
# only on the last layer

COPY --from=scripts templates/ templates/
COPY --from=scripts scripts/ scripts/
COPY --from=scripts configs/ configs/