# cumulus-aws

# Copyright (c) 2022 Intel Corporation
# SPDX-License-Identifier: Apache License 2.0

ARG RELEASE
FROM cumulus-cloud${RELEASE}

# Install AWS CLI 
RUN python3 -m pip install --no-cache-dir -r /PerfKitBenchmarker/perfkitbenchmarker/providers/aws/requirements.txt

# Add cleanup script
COPY script/cleanup-aws.sh /usr/local/bin/cleanup

