# linpack-intel

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG RELEASE
ARG OS_VER=22.04
ARG OS_IMAGE=ubuntu

FROM linpack-base-intel${RELEASE} as base

FROM ${OS_IMAGE}:${OS_VER}

COPY --from=base / /

WORKDIR /root

COPY run_test_intel.sh run_test.sh

RUN mkfifo /export-logs

CMD  (bash run_test.sh; echo $? > status) 2>&1  | tee output.logs && \
     tar cf /export-logs status output.logs && \
     sleep infinity