# specjbb-2015-openjdk-17.0.1

# ###########################
# Package manager(s) version of open-jdk currently does not run on SPR machine out-of-the-box, due to libjvm.so mismatch. Instead download jdk version explictly from java.net
# ###########################

ARG ARCH
FROM specjbb-2015-scripts${ARCH}${RELEASE} AS scripts
FROM specjbb-2015-base${ARCH}${RELEASE}

ARG PACKAGE_ARCH
ARG OPENJDK_VER="jdk-17.0.1"
ARG OPENJDK_PKG="https://download.java.net/java/GA/jdk17.0.1/2a2082e5a09d4267845be086888add4f/12/GPL/openjdk-17.0.1_linux-${PACKAGE_ARCH}_bin.tar.gz"

ARG OPENJDK_INSTALL_DIR=/opt
WORKDIR ${OPENJDK_INSTALL_DIR}

RUN curl -L "${OPENJDK_PKG}" -o "${OPENJDK_VER}.tar.gz" && \
  tar -xvf "${OPENJDK_VER}.tar.gz" && \
  rm -f "${OPENJDK_VER}.tar.gz"

USER root
RUN cd ${OPENJDK_VER} && \
  update-alternatives --install /usr/bin/java java ${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin/java 2 && \
  update-alternatives --install /usr/bin/jar jar ${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin/jar 2 && \
  update-alternatives --install /usr/bin/javac javac ${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin/javac 2 && \
  update-alternatives --set jar ${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin/jar && \
  update-alternatives --set javac ${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin/javac
USER ${WORKLOAD_USER}

ENV JAVA_HOME=${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/ \
  JRE_HOME=${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/jre/ \
  PATH=${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/bin:$PATH:${OPENJDK_INSTALL_DIR}/${OPENJDK_VER}/jre/bin

WORKDIR /opt/pkb

COPY --from=scripts templates/ templates/
COPY --from=scripts scripts/ scripts/
COPY --from=scripts configs/ configs/