# nginx-client-openssl

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG RELEASE

FROM qatsw-crypto-base-ssl3-ubuntu${RELEASE}
RUN apt-get update && apt-get install -y wget libpcre3 systemd && apt-get clean
COPY run_openssl.sh /
RUN mkfifo /export-logs
CMD (/run_openssl.sh; echo $? > status) 2>&1 | tee output.logs && \
    tar cf /export-logs status output.logs && \
    sleep infinity
