# istio-envoy-forward-server
ARG NIGHTHAWK_VER="2256da19d138866ca82adff2de7c5a5071cb430e"
#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG NIGHTHAWK_IMAGE="envoyproxy/nighthawk-dev"

FROM ${NIGHTHAWK_IMAGE}:${NIGHTHAWK_VER}
RUN apk add util-linux && apk add curl && apk add bash && apk add busybox-extras
