# terraform-tencent

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG RELEASE
FROM terraform-static${RELEASE}

# Install TCCLI 
ARG TENCENT_CLI_VER=3.0.871.1
ARG TENCENT_CLI_REPO=conda
RUN /opt/conda/bin/python3 -m pip install --no-cache-dir tccli==${TENCENT_CLI_VER}

# Add cleanup script
RUN echo "alias cleanup=/opt/csp/script/cleanup-tencent.sh" >> /etc/bash.bashrc
