#!/bin/bash
#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

# General Configurations
WORKLOAD=${WORKLOAD:-"nginx-dlb"}

# DLB Accelerator Configurations
DLB_ACC=${1:-disable}

# Cache Server Configurations
CACHE_SERVER_WORKER=${CACHE_SERVER_WORKER:-"1"}
CACHE_SERVER_CORE=${CACHE_SERVER_CORE:-"1"}
CACHE_TYPE=${CACHE_TYPE:-"disk"}
# Content Server Configurations
CONTENT_SERVER_WORKER=${CONTENT_SERVER_WORKER:-"1"}
CONTENT_SERVER_CORE=${CONTENT_SERVER_CORE:-"1"}

# WRK Client Configurations
WRK_CORE=${WRK_CORE:-"1"}
WRK_THREADS=${WRK_THREADS:-"1"}
FILE_SIZE=${FILE_SIZE:-"1MB"}
if [ $FILE_SIZE != "10KB" ] && [ $FILE_SIZE != "100KB" ] && [ $FILE_SIZE != "1MB" ] && [ $FILE_SIZE != "mix" ]; then
  echo "File size not supported. Only 10KB/100KB/1MB/mix are supported. Exit. "
fi
WRK_DURATION=${WRK_DURATION:-"30"}
WRK_TEXT_CONNECTIONS=${WRK_TEXT_CONNECTIONS:-"100"}
WRK_AUDIO_CONNECTIONS=${WRK_AUDIO_CONNECTIONS:-"100"}
WRK_VIDEO_CONNECTIONS=${WRK_VIDEO_CONNECTIONS:-"100"}
USE_KUBERNETES_SERVICE=${USE_KUBERNETES_SERVICE:-"false"}

# Overwrite parameters
DIR="$( cd "$( dirname "$0" )" &> /dev/null && pwd )"
. "$DIR/../../script/overwrite.sh"

# Workload Setting
WORKLOAD_PARAMS=(DLB_ACC \
                 CACHE_SERVER_WORKER CACHE_SERVER_CORE CACHE_TYPE\
                 CONTENT_SERVER_WORKER CONTENT_SERVER_CORE \
                 WRK_CORE WRK_THREADS FILE_SIZE WRK_DURATION WRK_TEXT_CONNECTIONS WRK_AUDIO_CONNECTIONS WRK_VIDEO_CONNECTIONS USE_KUBERNETES_SERVICE)

# Kubernetes Setting
RECONFIG_OPTIONS="-DWORKLOAD=$WORKLOAD -DDLB_ACC=$DLB_ACC \
                  -DCACHE_SERVER_WORKER=$CACHE_SERVER_WORKER -DCACHE_SERVER_CORE=$CACHE_SERVER_CORE -DCACHE_TYPE=$CACHE_TYPE\
                  -DCONTENT_SERVER_WORKER=$CONTENT_SERVER_WORKER -DCONTENT_SERVER_CORE=$CONTENT_SERVER_CORE \
                  -DWRK_CORE=$WRK_CORE -DWRK_THREADS=$WRK_THREADS -DFILE_SIZE=$FILE_SIZE -DWRK_DURATION=$WRK_DURATION \
                  -DWRK_TEXT_CONNECTIONS=$WRK_TEXT_CONNECTIONS -DWRK_AUDIO_CONNECTIONS=$WRK_AUDIO_CONNECTIONS -DWRK_VIDEO_CONNECTIONS=$WRK_VIDEO_CONNECTIONS -DUSE_KUBERNETES_SERVICE=$USE_KUBERNETES_SERVICE"

JOB_FILTER="job-name=wrk-client"

# Script Setting
SCRIPT_ARGS="$FILE_SIZE"

. "$DIR/../../script/validate.sh"
