# qatsw-crypto-base-ssl3-ubuntu-24.04.1

#
# Apache v2 license
# Copyright (C) 2023 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
ARG OS_VER=24.04
ARG OS_IMAGE=ubuntu
FROM ${OS_IMAGE}:${OS_VER} AS build

RUN apt-get update && apt-get install -y git gcc g++ cmake make automake autoconf libtool nasm yasm perl zlib1g-dev pkg-config

ARG OPENSSL_VER=3.1.4
ARG OPENSSL_REPO=https://github.com/openssl/openssl.git
RUN git clone --depth 1 -b openssl-${OPENSSL_VER} ${OPENSSL_REPO} openssl && \
    cd openssl && \
    ./Configure --openssldir=/etc/ssl/ && \
    make -j && \
    make install

ARG IPP_CRYPTO_VER="ippcp_2021.10.0"
ARG IPP_CRYPTO_REPO="https://github.com/intel/ipp-crypto"
RUN git clone --depth 1 -b ${IPP_CRYPTO_VER} ${IPP_CRYPTO_REPO} && \
    cd /ipp-crypto/sources/ippcp/crypto_mb && \
    cmake . -B"../build" \
    -DOPENSSL_INCLUDE_DIR=/usr/local/include/openssl \
    -DOPENSSL_CRYPTO_LIBRARY=/usr/local/lib64/libcrypto.so.3 -DOPENSSL_LIBRARIES=/usr/local/lib64 \
    -DOPENSSL_ROOT_DIR=/usr/local/bin/openssl && \
    cd ../build && \
    make crypto_mb && make install

ARG IPSEC_MB_VER="v1.5"
ARG IPSEC_MB_REPO="https://github.com/intel/intel-ipsec-mb"
RUN git clone --depth 1 -b ${IPSEC_MB_VER} ${IPSEC_MB_REPO} && \
    cd intel-ipsec-mb && \
    make && make install LIB_INSTALL_DIR=/usr/local/lib

ENV PKG_CONFIG_PATH=/usr/local/lib64/pkgconfig/

ARG QATENGINE_VER="v1.5.0"
ARG QATENGINE_REPO="https://github.com/intel/QAT_Engine"
RUN git clone --depth 1 -b ${QATENGINE_VER} ${QATENGINE_REPO} && \
    cd QAT_Engine && \
    ./autogen.sh && \
    ./configure \
    --with-openssl_install_dir=/usr/local/ \
    --enable-qat_sw  && \
    make && make install

FROM ${OS_IMAGE}:${OS_VER}
RUN apt-get update && apt-get install -y numactl zlib1g

COPY --from=build /usr/local /usr/local
COPY --from=build /etc/ssl /etc/ssl
COPY --from=build /QAT_Engine/LICENSE /usr/share/package-licenses/QAT_Engine/LICENSE
COPY --from=build /ipp-crypto/LICENSE /usr/share/package-licenses/ipp-crypto/LICENSE
COPY --from=build /intel-ipsec-mb/LICENSE /usr/share/package-licenses/intel-ipsec-mb/LICENSE

RUN echo "/usr/lib/" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig && \
    echo "/usr/lib64/" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig && \
    echo "/usr/local/lib/" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig && \
    echo "/usr/local/lib64/" >> /etc/ld.so.conf.d/all-libs.conf && ldconfig

ENV OPENSSL_ENGINES=/usr/local/lib64/engines-3

