#!/bin/bash -e

collectd_bin="/usr/sbin/collectd"
collectd_conf="$PROJECTROOT/script/docker/trace/collectd.conf"
sudo_password_required

collectd_start () {
    if [ -x "$collectd_bin" ]; then
        mkdir -p "$1-collectd/csv"
        cd "$1-collectd"
        if is_roi collectd $2 ${1##*-} TRACE_START; then
            sed "/<Plugin csv>/,/</{s|DataDir.*|DataDir \"$1-collectd/csv\"|}" "$collectd_conf" > collectd.conf
            echo "$DEV_SUDO_PASSWORD" | sudo -S bash -c "$collectd_bin -C collectd.conf -f > collectd.logs 2>&1 & echo \$! > collectd.pid"
            echo "collectd started"
        fi
    fi
}

collectd_stop () {
    if [ -d "$1-collectd" ]; then
        cd "$1-collectd"
        if is_roi collectd $2 ${1##*-} TRACE_STOP; then
            echo "$DEV_SUDO_PASSWORD" | sudo -S kill $(cat collectd.pid) || true
            tail -f --pid=$(cat collectd.pid) /dev/null
            echo "$DEV_SUDO_PASSWORD" | sudo -S chown -R $(id -u):$(id -g) "$1-collectd"
            rm -f collectd.pid
            echo "collectd stopped"
        fi
    fi
}

collectd_collect () {
    if [ -r "$1-collectd/TRACE_STOP" ]; then
        cd "$1-collectd"
        if [ -d csv ]; then
            host="$(cd csv; ls -1)"
            cp -rf "csv/$host"/* . || true
            rm -rf csv
        fi
    fi
}
