#!/bin/bash -e

perf_record_options="-a -g"
perf_report_options="--header"
perf_script_options=""
sudo_password_required

perf_start () {
    mkdir -p "$1-perf"
    cd "$1-perf"
    if is_roi perf $2 ${1##*-} TRACE_START; then
        echo "$DEV_SUDO_PASSWORD" | sudo -S bash -c "perf record $perf_record_options --output perf-$2.record -- sleep infinity & echo \$! > perf.pid"
        echo "perf started"
    fi
}

perf_stop () {
    if [ -d "$1-perf" ]; then
        cd "$1-perf"
        if is_roi perf $2 ${1##*-} TRACE_STOP; then
            echo "$DEV_SUDO_PASSWORD" | sudo -S kill $(cat perf.pid) || true
            tail -f --pid=$(cat perf.pid) /dev/null || true
            echo "$DEV_SUDO_PASSWORD" | sudo -S chown -R $(id -u):$(id -g) "$1-perf"
            rm -f perf.pid || true
            echo "perf stopped"
        fi
    fi
}

perf_collect () {
    if [ -d "$1-perf" ]; then
        cd "$1-perf"
        for record in perf-*.record; do
            [ -e $record ] || continue
            perf report $perf_report_options -i $record > ${record/.record/.report} || true
            perf script $perf_script_options -i $record > $record.out || true
        done
    fi
}

