#!/bin/bash -e

perfspect_metrics_options=""
sudo_password_required

perfspect_start () {
    mkdir -p "$1-perfspect"
    cd "$1-perfspect"
    if is_roi perfspect $2 ${1##*-} TRACE_START; then
        mkdir -p roi-$2
        echo "$DEV_SUDO_PASSWORD" | sudo -S bash -c "perfspect metrics --format csv $perfspect_metrics_options --noupdate --output roi-$2 > perfspect.logs 2>&1 & echo \$! > perfspect.pid"
        echo "perfspect started"
    fi
}

perfspect_stop () {
    if [ -d "$1-perfspect" ]; then
        cd "$1-perfspect"
        if is_roi perfspect $2 ${1##*-} TRACE_STOP; then
            echo "$DEV_SUDO_PASSWORD" | sudo -S kill -s SIGINT $(cat perfspect.pid) || true
            tail -f --pid=$(cat perfspect.pid) /dev/null || true
            echo "$DEV_SUDO_PASSWORD" | sudo -S chown -R $(id -u):$(id -g) "$1-perfspect"
            rm -f perfspect.pid || true
            echo "perfspect stopped"
        fi
    fi
}

perfspect_collect () {
    cd "$1-perfspect"
}
